config/routes.rb
SignupSn::Application.routes.draw do
  root :to => 'application#home'
    
  resources :users do
    get :interstitial, :on => :collection
    get :index, :on => :collection
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include SinglesnetUser
  
  after_validation :construct_core_key, if: :new_record?
  after_validation :construct_full_url, unless: :new_record?
    
  attr_accessor :redirect_url, :flash_error, :shortcut
    
  def city_finder
    SinglesnetApi.find_city(zipcode)
  end
  
  def generate_captcha
    self.captcha_key = SinglesnetApi.captcha_generate
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def home
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :variation
  layout :nil
  layout 'application', :except => [:interstitial, :index]
  
  def new
    @user = User.new
    render "new_v#{@variation}"
  end
  
  def edit
    @user = User.find(session[:user_id])
    render "edit_v#{@variation}"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user.id, :variation => @variation)
    else 
      flash.now[:error] = @user.flash_error
      render "new_v#{@variation}"
    end
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(params[:user])
      session[:redirect_url] = @user.redirect_url
      redirect_to interstitial_users_url
    else
      render "edit_v#{@variation}"
    end
  end
  
  def interstitial
  end
  
  def index
  end
  
  private
  
  def variation
    @variation = (params[:variation] || 1)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/singlesnet_helper.rb
module SinglesnetHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/application/_footer.html.erb
<div id="ftr" class="group">
  <div class="wrap">
    <ul>
      <li>
        <h5>Free Online Dating</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quis turpis nulla. Maecenas vestibulum libero odio, at vehicula dui. Cras sodales ipsum vitae enim bibendum non euismod felis pretium. Quisque sed risus arcu. In sed dui magna. Ut cursus aliquam mauris convallis laoreet. Proin luctus magna vel diam aliquam eget consequat nisi aliquam. Quisque fringilla mauris sit amet turpis pulvinar sodales.</p>
      </li>
      <li>
        <h5>Online Singles</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quis turpis nulla. Maecenas vestibulum libero odio, at vehicula dui. Cras sodales ipsum vitae enim bibendum non euismod felis pretium. Quisque sed risus arcu. In sed dui magna. Ut cursus aliquam mauris convallis laoreet. Proin luctus magna vel diam aliquam eget consequat nisi aliquam. Quisque fringilla mauris sit amet turpis pulvinar sodales.</p>
      </li>
      <li class="last">
        <h5>Online Chat</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quis turpis nulla. Maecenas vestibulum libero odio, at vehicula dui. Cras sodales ipsum vitae enim bibendum non euismod felis pretium. Quisque sed risus arcu. In sed dui magna. Ut cursus aliquam mauris convallis laoreet. Proin luctus magna vel diam aliquam eget consequat nisi aliquam. Quisque fringilla mauris sit amet turpis pulvinar sodales.</p>
      </li>
    </ul>
  </div>
</div>

app/views/application/home.html.erb
<%= link_to("Create a new profile!", users_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
  
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>SinglesNet</title>
<%= stylesheet_link_tag("v#{@variation}") if @variation %>
<%= javascript_include_tag("application") %>
<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="/assets/jquery.selectBox.min.js" type="text/javascript"></script> -->
<script type="text/javascript">
			
			$(document).ready( function() {
				
				$("SELECT").selectBox('create');
				
			});
			
			errors = <%= flash.now[:error].to_json %>	
			
			
</script>
</head>
  <body>
    <%= yield %>
    <%= render "footer" %>
  </body>
</html>

app/views/users/_edit_form.html.erb
<%= form_for @user, :url => { :action => :update, :variation => @variation } do |f| %>

<% if @user.errors.any? %>
  <div class="profile_error">
    <% @user.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  </div>
<% end %>  

<div class="profileQuestion" id="P_RACE">
  <%= f.label(:race, "Ethnicity:") %>
  <%= f.select(:race, {
  "Please Select" => "",   
  "Black / African descent" => "1", 
  "Asian" => "2", 
  "White / Caucasian" => "3", 
  "East Indian" => "4", 
  "Hispanic / Latino" => "5", 
  "Middle Eastern" => "6", 
  "Multi-racial" => "7", 
  "Native American" => "8", 
  "Pacific Islander" => "9", 
  "Other" => "10" })  %>
</div>
<div class="profileQuestion" id="P_EYE_COLOR">
  <%= f.label(:eye, "Eye Color:") %>
  <%= f.select(:eye, {
  "Please Select" => "",  
  "Blue" => "1", 
  "Brown" => "2", 
  "Green" => "3", 
  "Gray" => "4", 
  "Hazel" => "5", 
  "Other" => "6" 
  })  %>
</div>
<div class="profileQuestion" id="P_HAIR_COLOR">
  <%= f.label(:hair, "Hair Color:") %>
  <%= f.select(:hair, {
  "Please Select" => "",  
  "Auburn / Red" => "1", 
  "Bald" => "2", 
  "Black" => "3", 
  "Blonde" => "4", 
  "Dark blonde" => "5", 
  "Dark brown" => "6", 
  "Gray / White" => "7", 
  "Light brown" => "8", 
  "Salt and pepper gray" => "9" 
  })  %>
</div>
<div class="profileQuestion" id="P_BODY_TYPE">
  <%= f.label(:body, "Body Type:") %>
  <%= f.select(:body, {
  "Please Select" => "",
  "Average" => "1", 
  "Slim / Slender" => "2", 
  "Fit / Athletic" => "3", 
  "Few extra pounds" => "4"})  %>
</div>
<div class="profileQuestion" id="P_HEIGHT">
  <%= f.label(:height, "Height:")%>
  <%= f.select(:height, {
  "Please Select" => "",
  "4\' 4\"" => "1",
  "4\' 5\"" => "2",
  "4\' 6\"" => "3",
  "4\' 7\"" => "4",
  "4\' 8\"" => "5",
  "4\' 9\"" => "6",
  "4\' 10\"" => "7",
  "4\' 11\"" => "8",
  "5\'" => "9",
  "5\' 1\"" => "10",
  "5\' 2\"" => "11",
  "5\' 3\"" => "12",
  "5\' 4\"" => "13",
  "5\' 5\"" => "14",
  "5\' 6\"" => "15",
  "5\' 7\"" => "16",
  "5\' 8\"" => "17",
  "5\' 9\"" => "18",
  "5\' 10\"" => "19",
  "5\' 11\"" => "20",
  "6\'" => "21",
  "6\' 1\"" => "22",
  "6\' 2\"" => "23",
  "6\' 3\"" => "24",
  "6\' 4\"" => "25",
  "6\' 5\"" => "26",
  "6\' 6\"" => "27",
  "6\' 7\"" => "28",
  "6\' 8\"" => "29"
  })%>
</div>
<div class="profileQuestion" id="P_OCCUPATION">
  <%= f.label(:occupation, "Occupation:")%>
  <%= f.select(:occupation, {
    "Please Select" => "",
    "Accounting" => "1",
  "Actor / Actress" => "2",
  "Administrative" => "3",
  "Advertising" => "4",
  "Agriculture" => "5",
  "Architect" => "6",
  "Arts" => "7",
  "Banking" => "8",
  "Biotechnology" => "9",
  "Business Owner" => "10",
  "Computers, Hard" => "12",
  "Computers, Soft" => "13",
  "Construction" => "14",
  "Consulting" => "15",
  "Customer Service" => "16",
  "Engineering" => "17",
  "Entrepreneur" => "18",
  "Financial Services" => "19",
  "Government" => "20",
  "Graphic Design" => "21",
  "Health-care" => "22",
  "Hospitality / Tourism" => "23",
  "Human Resources" => "25",
  "Info. Technology" => "26",
  "Insurance" => "27",
  "Internet" => "28",
  "Law Enforcement" => "29",
  "Legal" => "30",
  "Manufacturing" => "31",
  "Marketing" => "32",
  "Military" => "33",
  "Maintenance" => "34",
  "Nanny / Child Care" => "35",
  "Nursing" => "36",
  "Pharmaceutical" => "37",
  "Public Relations" => "38",
  "Real Estate" => "39",
  "Restaurant" => "40",
  "Recruiting" => "41",
  "Retail" => "42",
  "Sales" => "43",
  "Self-Employed" => "44",
  "Science" => "45",
  "Social Services" => "11",
  "Sports" => "46",
  "Student" => "47",
  "Teacher" => "48",
  "Telecommunications" => "49",
  "Transportation" => "50",
  "Writer / Editor" => "51",
  "Retired" => "52"}
  )  %>
</div>
<div class="profileQuestion" id="P_ABOUT_ME">
  <%= f.label(:about, "About Me:") %>
  </br>
  <%= f.text_area(:about, :cols => 48, :rows => 8)  %>
</div>
<div class="login-button">
  <%= f.submit 'Create My Profile', id: "user_submit" %>
</div>
<% end %>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div class="<%= css_class %>">
    <% @user.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for @user, :url => { :action => :create, :variation => @variation } do |f| %>
<h2>Lorem ipsum dolor headline</h2>
<%= render "errors", :css_class => "core_error" %>
<div class='formCore'>
  <div class="formSection" id="CORE_SECTION_SEEKING">
    <div class="formQuestion" id="Q_SEX">
      <%= f.label(:sex, "I am a")%>
      <%= f.select(:sex, {"Man" => "M", "Woman" => "F"})%>
    </div>
    <div class="formQuestion" id="Q_SEX_SEEKING">
      <%= f.label(:sex_seeking, "seeking a") %>
      <%= f.select(:sex_seeking, {"Woman" => "F", "Man" => "M"}) %>
    </div>
    <div class="formQuestion" id="Q_ZIPCODE">
      <%= f.label(:zipcode, "Zipcode") %>
      <%= f.text_field(:zipcode) %>
    </div>
    <div class="formQuestion" id="Q_BIRTHDAY">
      <label for="birthday">Birthday:</label>
      <%= f.select(:birthday_month, {
        "Jan" => "01", 
        "Feb" => "02", 
        "Mar" => "03", 
        "Apr" => "04", 
        "May" => "05", 
        "Jun" => "06", 
        "Jul" => "07", 
        "Aug" => "08", 
        "Sep" => "09", 
        "Oct" => "10", 
        "Nov" => "11", 
        "Dec" => "12"} 
        ) %>
        <%= f.select(:birthday_day, {
          "01" => "01", 
          "02" => "02", 
          "03" => "03", 
          "04" => "04", 
          "05" => "05", 
          "06" => "06", 
          "07" => "07", 
          "08" => "08", 
          "09" => "09", 
          "10" => "10", 
          "11" => "11", 
          "12" => "12", 
          "13" => "13", 
          "14" => "14", 
          "15" => "15", 
          "16" => "16", 
          "17" => "17", 
          "18" => "18", 
          "19" => "19", 
          "20" => "20", 
          "21" => "21", 
          "22" => "22", 
          "23" => "23", 
          "24" => "24", 
          "25" => "25", 
          "26" => "26", 
          "27" => "27", 
          "28" => "28", 
          "29" => "29", 
          "30" => "30", 
          "31" => "31"}) %>
          <%= f.select(:birthday_year, {
            "1919" => "1919", 
            "1920" => "1920", 
            "1921" => "1921", 
            "1922" => "1922", 
            "1923" => "1923", 
            "1924" => "1924", 
            "1925" => "1925", 
            "1926" => "1926", 
            "1927" => "1927", 
            "1928" => "1928", 
            "1929" => "1929", 
            "1930" => "1930", 
            "1931" => "1931", 
            "1932" => "1932", 
            "1933" => "1933", 
            "1934" => "1934", 
            "1935" => "1935", 
            "1936" => "1936", 
            "1937" => "1937", 
            "1938" => "1938", 
            "1939" => "1939", 
            "1940" => "1940", 
            "1941" => "1941", 
            "1942" => "1942", 
            "1943" => "1943", 
            "1944" => "1944", 
            "1945" => "1945", 
            "1946" => "1946", 
            "1947" => "1947", 
            "1948" => "1948", 
            "1949" => "1949", 
            "1950" => "1950", 
            "1951" => "1951", 
            "1952" => "1952", 
            "1953" => "1953", 
            "1954" => "1954", 
            "1955" => "1955", 
            "1956" => "1956", 
            "1957" => "1957", 
            "1958" => "1958", 
            "1959" => "1959", 
            "1960" => "1960", 
            "1961" => "1961", 
            "1962" => "1962", 
            "1963" => "1963", 
            "1964" => "1964", 
            "1965" => "1965", 
            "1966" => "1966", 
            "1967" => "1967", 
            "1968" => "1968", 
            "1969" => "1969", 
            "1970" => "1970", 
            "1971" => "1971", 
            "1972" => "1972", 
            "1973" => "1973", 
            "1974" => "1974", 
            "1975" => "1975", 
            "1976" => "1976", 
            "1977" => "1977", 
            "1978" => "1978", 
            "1979" => "1979", 
            "1980" => "1980", 
            "1981" => "1981", 
            "1982" => "1982", 
            "1983" => "1983", 
            "1984" => "1984", 
            "1985" => "1985", 
            "1986" => "1986", 
            "1987" => "1987", 
            "1988" => "1988", 
            "1989" => "1989", 
            "1990" => "1990", 
            "1991" => "1991", 
            "1992" => "1992", 
            "1993" => "1993", 
            "1994" => "1994"})%>
          </div>
        </div>
        <div class="formSection" id="CORE_SECTION_ACCOUNT_DATA">
          <div class="formQuestion" id="Q_SCREENNAME">
            <%= f.label :username %>
            <%= f.text_field(:username) %>
          </div>
          <div class="formQuestion" id="Q_PASSWORD">
            <%= f.label :password %>
            <%= f.password_field(:password)  %>
          </div>
          <div class="formQuestion" id="Q_EMAIL">
            <%= f.label :email %>
            <%= f.text_field(:email) %>
          </div>
        </div>
      </div>
      <div id="disclaimer">
        <p id="legal">By continuing I certify I am at least 18 years old and have read and agree to the Singlesnet <a target="_blank" href="http://www.singlesnet.com/?setlocation=help&setarea=privacy_popup&from=signup">privacy policy</a> and <a target="_blank" href="http://www.singlesnet.com/?setlocation=help&setarea=membership_popup&from=signup">membership agreement</a>.</p>
        <p>Are you human? Type in the characers below:</p>
        <p style='display:none'>
          <%= @user.generate_captcha %>
          <%= f.hidden_field(:captcha_key) %>
        </p>
        <p>
          <img src= <%= SinglesnetApi.captcha_img_url(@user.captcha_key) %> alt="CAPTCHA" />
        </p>
        <p>
          <%= f.text_field(:captcha_answer)  %>
          </p>
        <div class="button" id="button" type="submit">
          <%= f.submit 'Continue', id: "user_submit" %>
        </div>
      </div>
      <% end %>

app/views/users/edit_v1.html.erb
<div id="hdr">
  <h1>Singlesnet.com</h1>
</div>
<div id="content" class="wrap profile_details">

  <h2>Almost Done! Create your profile below.</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sit amet sem nulla. Aliquam erat volutpat.</p>

  <%= render "edit_form" %>
	
</div>

app/views/users/edit_v2.html.erb
<div id="hdr">

	<div class="wrap">

		<h1>Singlesnet</h1>

	</div>

</div>

<div id="wrap">

<div id="profile" class="group">

<h2>Lorem ipsum dolor create profile.</h2>

<div id="form">
	<h3>Create Your Profile</h3>
	
	<%= render "edit_form" %>
	
	<div id="about_tips">
	<p>About Me Tips:</p>
	<ul>
		<li>Lorem ipsum dolor lorem</li>
		<li>Lorem ipsum dolor lorem</li>
		<li>Lorem ipsum dolor lorem</li>
	</ul>
	</div>
	
</div>

	
</div>
	
</div>

app/views/users/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
  <!-- Google Website Optimizer Control Script -->
  <script>
  function utmx_section(){}function utmx(){}
  (function(){var k='0851624155',d=document,l=d.location,c=d.cookie;function f(n){
  if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.indexOf(';',i);return escape(c.substring(i+n.
  length+1,j<0?c.length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;
  d.write('<sc'+'ript src="'+
  'http'+(l.protocol=='https:'?'s://ssl':'://www')+'.google-analytics.com'
  +'/siteopt.js?v=1&utmxkey='+k+'&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='
  +new Date().valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
  '" type="text/javascript" charset="utf-8"></sc'+'ript>')})();
  </script><script>utmx("url",'A/B');</script>
  <!-- End of Google Website Optimizer Control Script -->
  <!-- Google Website Optimizer Tracking Script -->
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['gwo._setAccount', 'UA-26188677-1']);
    _gaq.push(['gwo._trackPageview', '/0851624155/test']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <!-- End of Google Website Optimizer Tracking Script -->
  
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>index</title>
	<meta name="generator" content="TextMate http://macromates.com/">
	<meta name="author" content="Nick Coelius">
	<!-- Date: 2012-02-17 -->
</head>
<body>
  <script>
    redirect_url = "<%= new_user_path.html_safe %>";
    window.onload = function() {
      window.location.href = redirect_url
    };
  </script>
</body>
</html>

app/views/users/interstitial.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <!-- Google Website Optimizer Tracking Script -->
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['gwo._setAccount', 'UA-26188677-1']);
    _gaq.push(['gwo._trackPageview', '/0851624155/goal']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <!-- End of Google Website Optimizer Tracking Script -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>SinglesNet</title>
  <!-- JS GOES HERE -->
</head>

<script>
  redirect_url = "<%= session[:redirect_url].html_safe %>";
  window.onload = function() {
    window.location.href = redirect_url
  };
</script>


</html>

app/views/users/new_v2.html.erb
<!-- Google Website Optimizer Tracking Script -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['gwo._setAccount', 'UA-26188677-1']);
  _gaq.push(['gwo._trackPageview', '/0851624155/test']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!-- End of Google Website Optimizer Tracking Script -->

<div id="hdr">

  <div class="wrap">

    <h1>Singlesnet</h1>

  </div>

</div>

<div id="wrap">

  <div id="content" class="group">

    <div id="form">
      <h3>Join SinglesNet, it's FREE</h3>
      <%= render "new_form" %>
    </div>

    <h2>Meet singles near you!</h2>
    <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Nulla sodales velit eu massa egestas feugiat.  Lorem ipsum dolor ipsum dolor sit amet.</h3>


  </div>

  <div id="benefits" class="group">
    <h3>Free Member Benefits</h3>
    <ul>
      <li> <%= image_tag("v2/icon_chat.png", :alt => "Chat With Thousands") %>
        <h4>Chat With Thousands</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </li>
      <li> <%= image_tag("v2/icon_message.png", :alt => "Email Featured Members") %>
        <h4>Email Featured Members</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </li>
      <li> <%= image_tag("v2/icon_profile.png", :alt => "View Member Profiles") %>
        <h4>View Member Profiles</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </li>
      <li class="last"> <%= image_tag("v2/icon_singles.png", :alt => "Proprietary Matching") %>
        <h4>Proprietary Matching</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </li>
    </ul>
  </div>

</div>